/**
 * Centralized State Machine and SLA Engine for FIR Investigation & Master Watchlist Workflow
 */

const INVESTIGATION_STATES = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  ADMIN_REVIEW: 'ADMIN_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CORRECTION_REQUIRED: 'CORRECTION_REQUIRED',
  WATCHLIST_ACTIVE: 'WATCHLIST_ACTIVE',
  ASSIGNED_TO_DEPARTMENTS: 'ASSIGNED_TO_DEPARTMENTS',
  SEARCHING: 'SEARCHING',
  MATCH_FOUND: 'MATCH_FOUND',
  NO_MATCH: 'NO_MATCH',
  RESULT_SUBMITTED: 'RESULT_SUBMITTED',
  ADMIN_VALIDATION: 'ADMIN_VALIDATION',
  MORE_EVIDENCE_REQUIRED: 'MORE_EVIDENCE_REQUIRED',
  FORWARDED_TO_ORIGIN: 'FORWARDED_TO_ORIGIN',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
};

const ALLOWED_TRANSITIONS = {
  [INVESTIGATION_STATES.DRAFT]: [
    INVESTIGATION_STATES.SUBMITTED,
    INVESTIGATION_STATES.CANCELLED,
  ],
  [INVESTIGATION_STATES.SUBMITTED]: [
    INVESTIGATION_STATES.ADMIN_REVIEW,
    INVESTIGATION_STATES.APPROVED,
    INVESTIGATION_STATES.REJECTED,
    INVESTIGATION_STATES.CORRECTION_REQUIRED,
    INVESTIGATION_STATES.CANCELLED,
  ],
  [INVESTIGATION_STATES.ADMIN_REVIEW]: [
    INVESTIGATION_STATES.APPROVED,
    INVESTIGATION_STATES.REJECTED,
    INVESTIGATION_STATES.CORRECTION_REQUIRED,
    INVESTIGATION_STATES.CANCELLED,
  ],
  [INVESTIGATION_STATES.CORRECTION_REQUIRED]: [
    INVESTIGATION_STATES.SUBMITTED,
    INVESTIGATION_STATES.CANCELLED,
  ],
  [INVESTIGATION_STATES.REJECTED]: [
    INVESTIGATION_STATES.ADMIN_REVIEW,
    INVESTIGATION_STATES.CLOSED,
  ],
  [INVESTIGATION_STATES.APPROVED]: [
    INVESTIGATION_STATES.WATCHLIST_ACTIVE,
    INVESTIGATION_STATES.ASSIGNED_TO_DEPARTMENTS,
    INVESTIGATION_STATES.CLOSED,
  ],
  [INVESTIGATION_STATES.WATCHLIST_ACTIVE]: [
    INVESTIGATION_STATES.ASSIGNED_TO_DEPARTMENTS,
    INVESTIGATION_STATES.SEARCHING,
    INVESTIGATION_STATES.MATCH_FOUND,
    INVESTIGATION_STATES.RESOLVED,
    INVESTIGATION_STATES.CLOSED,
  ],
  [INVESTIGATION_STATES.ASSIGNED_TO_DEPARTMENTS]: [
    INVESTIGATION_STATES.SEARCHING,
    INVESTIGATION_STATES.MATCH_FOUND,
    INVESTIGATION_STATES.NO_MATCH,
    INVESTIGATION_STATES.RESULT_SUBMITTED,
    INVESTIGATION_STATES.CLOSED,
  ],
  [INVESTIGATION_STATES.SEARCHING]: [
    INVESTIGATION_STATES.MATCH_FOUND,
    INVESTIGATION_STATES.NO_MATCH,
    INVESTIGATION_STATES.RESULT_SUBMITTED,
  ],
  [INVESTIGATION_STATES.NO_MATCH]: [
    INVESTIGATION_STATES.SEARCHING,
    INVESTIGATION_STATES.MATCH_FOUND,
    INVESTIGATION_STATES.RESOLVED,
    INVESTIGATION_STATES.CLOSED,
  ],
  [INVESTIGATION_STATES.MATCH_FOUND]: [
    INVESTIGATION_STATES.RESULT_SUBMITTED,
    INVESTIGATION_STATES.SEARCHING,
  ],
  [INVESTIGATION_STATES.RESULT_SUBMITTED]: [
    INVESTIGATION_STATES.ADMIN_VALIDATION,
    INVESTIGATION_STATES.FORWARDED_TO_ORIGIN,
    INVESTIGATION_STATES.MORE_EVIDENCE_REQUIRED,
    INVESTIGATION_STATES.REJECTED,
  ],
  [INVESTIGATION_STATES.ADMIN_VALIDATION]: [
    INVESTIGATION_STATES.FORWARDED_TO_ORIGIN,
    INVESTIGATION_STATES.MORE_EVIDENCE_REQUIRED,
    INVESTIGATION_STATES.REJECTED,
  ],
  [INVESTIGATION_STATES.MORE_EVIDENCE_REQUIRED]: [
    INVESTIGATION_STATES.RESULT_SUBMITTED,
    INVESTIGATION_STATES.SEARCHING,
  ],
  [INVESTIGATION_STATES.FORWARDED_TO_ORIGIN]: [
    INVESTIGATION_STATES.ACKNOWLEDGED,
    INVESTIGATION_STATES.RESOLVED,
  ],
  [INVESTIGATION_STATES.ACKNOWLEDGED]: [
    INVESTIGATION_STATES.RESOLVED,
    INVESTIGATION_STATES.SEARCHING,
    INVESTIGATION_STATES.CLOSED,
  ],
  [INVESTIGATION_STATES.RESOLVED]: [
    INVESTIGATION_STATES.CLOSED,
    INVESTIGATION_STATES.WATCHLIST_ACTIVE,
  ],
  [INVESTIGATION_STATES.CLOSED]: [],
  [INVESTIGATION_STATES.CANCELLED]: [],
};

/**
 * Standard SLA duration in hours based on priority
 */
const SLA_HOURS = {
  CRITICAL: 2,
  HIGH: 6,
  MEDIUM: 24,
  LOW: 72,
};

function calculateSlaDueAt(priority, fromDate = new Date()) {
  const p = String(priority || 'MEDIUM').toUpperCase();
  const hours = SLA_HOURS[p] || 24;
  return new Date(new Date(fromDate).getTime() + hours * 60 * 60 * 1000);
}

function calculateSlaRemaining(dueAt) {
  if (!dueAt) return { remainingMs: 0, text: 'No SLA', isBreached: false };
  const diff = new Date(dueAt).getTime() - Date.now();
  const isBreached = diff < 0;
  const absDiff = Math.abs(diff);

  const totalMinutes = Math.floor(absDiff / (1000 * 60));
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;

  const formatted = `${String(hours).padStart(2, '0')}h ${String(minutes).padStart(2, '0')}m`;
  return {
    remainingMs: diff,
    text: isBreached ? `Overdue by ${formatted}` : `${formatted} remaining`,
    isBreached,
    hours,
    minutes,
  };
}

function validateTransition(currentStatus, nextStatus) {
  if (!currentStatus || !nextStatus) return false;
  if (currentStatus === nextStatus) return true;
  const allowed = ALLOWED_TRANSITIONS[currentStatus] || [];
  return allowed.includes(nextStatus);
}

module.exports = {
  INVESTIGATION_STATES,
  ALLOWED_TRANSITIONS,
  SLA_HOURS,
  calculateSlaDueAt,
  calculateSlaRemaining,
  validateTransition,
};
