const GapAnalysisReport = require('../models/GapAnalysisReport');
const Department = require('../models/Department');
const Notification = require('../models/Notification');
const SystemAuditLog = require('../models/SystemAuditLog');
const { performGapAnalysis } = require('../services/gapAnalysisService');
const logger = require('../utils/logger');

/**
 * Generate a sequential/unique Report ID: GA-YYYY-XXXX
 */
async function generateReportId() {
  const year = new Date().getFullYear();
  const count = await GapAnalysisReport.countDocuments();
  const seq = String(count + 1).padStart(4, '0');
  return `GA-${year}-${seq}`;
}

/**
 * 1. RUN GAP ANALYSIS & GENERATE PERSISTED REPORT
 * @route POST /api/gap-analysis/analyze
 * @access Admin only
 */
const runAnalysis = async (req, res) => {
  try {
    const {
      locationName,
      latitude,
      longitude,
      radiusMeters,
      district,
      city,
      filters = {},
    } = req.body;

    if (!latitude || !longitude || !radiusMeters) {
      return res.status(400).json({
        success: false,
        message: 'Location coordinates (latitude, longitude) and analysis radius are required.',
      });
    }

    const lat = parseFloat(latitude);
    const lng = parseFloat(longitude);
    const radius = parseInt(radiusMeters, 10);

    if (isNaN(lat) || isNaN(lng) || isNaN(radius) || radius <= 0) {
      return res.status(400).json({
        success: false,
        message: 'Invalid numerical values for latitude, longitude, or radius.',
      });
    }

    // Execute authoritative GIS calculation engine
    const analysisResult = await performGapAnalysis({
      locationName: locationName || `${lat.toFixed(4)}, ${lng.toFixed(4)}`,
      latitude: lat,
      longitude: lng,
      radiusMeters: radius,
      district: district || 'Ahmedabad',
      city: city || '',
      filters,
    });

    const reportId = await generateReportId();

    // Persist as a GapAnalysisReport document
    const newReport = await GapAnalysisReport.create({
      reportId,
      location: analysisResult.location,
      radiusMeters: analysisResult.radiusMeters,
      filters,
      summary: analysisResult.summary,
      scoreFactors: analysisResult.scoreFactors,
      clusteringAnalysis: analysisResult.clusteringAnalysis,
      gridCells: analysisResult.gridCells,
      gaps: analysisResult.gaps,
      responsibleDepartment: analysisResult.responsibleDepartment,
      candidateDepartments: analysisResult.candidateDepartments,
      status: 'GENERATED',
      createdBy: {
        userId: req.user._id,
        name: req.user.name,
        role: req.user.role,
        email: req.user.email || '',
      },
      statusHistory: [
        {
          status: 'GENERATED',
          changedAt: new Date(),
          changedBy: req.user.name,
          notes: 'GIS Gap Analysis generated by Administrator',
        },
      ],
    });

    // Record audit log
    await SystemAuditLog.create({
      user: req.user._id,
      userName: req.user.name,
      userEmail: req.user.email,
      role: 'ADMIN',
      department: req.user.department || 'Government of Gujarat',
      action: 'GAP_ANALYSIS_GENERATED',
      resource: 'GapAnalysisReport',
      resourceId: reportId,
      description: `Generated GIS Gap Analysis for ${analysisResult.location.name} (Radius: ${radius}m, Score: ${analysisResult.summary.coverageScore}/100, Gaps: ${analysisResult.summary.criticalGaps})`,
      ipAddress: req.ip || '127.0.0.1',
      userAgent: req.headers['user-agent'] || '',
    });

    res.status(201).json({
      success: true,
      message: 'Surveillance gap analysis completed successfully.',
      data: {
        ...newReport.toObject(),
        cameras: analysisResult.cameras,
      },
    });
  } catch (error) {
    logger.error(`Run gap analysis error: ${error.message}`);
    res.status(500).json({
      success: false,
      message: error.message || 'Surveillance gap analysis could not be completed. Please try again.',
    });
  }
};

/**
 * 2. LIST GAP ANALYSIS REPORTS
 * @route GET /api/gap-analysis
 * @access Authenticated (Role-isolated)
 */
const getReports = async (req, res) => {
  try {
    const { status, district, departmentCode, page = 1, limit = 20 } = req.query;
    const userRole = String(req.user.role || '').toUpperCase();
    const isAdmin = ['ADMIN', 'SUPERADMIN'].includes(userRole);

    const filter = {};

    // RBAC: Department users only see reports assigned to their department
    if (!isAdmin) {
      const userDept = (req.user.department || '').toUpperCase();
      if (!userDept) {
        return res.status(200).json({ success: true, data: { reports: [], total: 0 } });
      }
      // Match department code or name
      filter.$or = [
        { 'responsibleDepartment.code': userDept },
        { 'responsibleDepartment.name': new RegExp(userDept, 'i') },
      ];
      // Department users do not see un-sent drafts
      filter.status = { $in: ['SENT', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED'] };
    }

    if (status && status !== 'all') {
      filter.status = status;
    }
    if (district && district !== 'all') {
      filter['location.district'] = new RegExp(`^${district}$`, 'i');
    }
    if (departmentCode && departmentCode !== 'all') {
      filter['responsibleDepartment.code'] = departmentCode.toUpperCase();
    }

    const skip = (parseInt(page, 10) - 1) * parseInt(limit, 10);
    const [reports, total] = await Promise.all([
      GapAnalysisReport.find(filter)
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(parseInt(limit, 10))
        .select('-gridCells'), // Omit heavy grid cell coordinates from summary list
      GapAnalysisReport.countDocuments(filter),
    ]);

    res.status(200).json({
      success: true,
      data: {
        reports,
        total,
        page: parseInt(page, 10),
        pages: Math.ceil(total / parseInt(limit, 10)),
      },
    });
  } catch (error) {
    logger.error(`Get gap analysis reports error: ${error.message}`);
    res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * 3. GET SINGLE GAP ANALYSIS REPORT BY ID
 * @route GET /api/gap-analysis/:id
 * @access Authenticated (Role-isolated & IDOR prevented)
 */
const getReportById = async (req, res) => {
  try {
    const { id } = req.params;
    const userRole = String(req.user.role || '').toUpperCase();
    const isAdmin = ['ADMIN', 'SUPERADMIN'].includes(userRole);

    const report = await GapAnalysisReport.findOne({
      $or: [{ reportId: id }, { _id: id.match(/^[0-9a-fA-F]{24}$/) ? id : null }],
    });

    if (!report) {
      return res.status(404).json({
        success: false,
        message: 'Gap Analysis Report not found.',
      });
    }

    // Role authorization check (prevent IDOR)
    if (!isAdmin) {
      const userDept = (req.user.department || '').toUpperCase();
      const reportDept = (report.responsibleDepartment?.code || '').toUpperCase();
      const reportDeptName = (report.responsibleDepartment?.name || '').toUpperCase();

      const isMatchingDept =
        userDept &&
        (userDept === reportDept ||
          reportDeptName.includes(userDept) ||
          userDept.includes(reportDept));

      if (!isMatchingDept) {
        return res.status(403).json({
          success: false,
          message: 'Access Restricted: You are not authorized to view gap analysis reports dispatched to another department.',
        });
      }
    }

    // Record view audit log
    await SystemAuditLog.create({
      user: req.user._id,
      userName: req.user.name,
      userEmail: req.user.email,
      role: req.user.role,
      department: req.user.department || 'Government of Gujarat',
      action: 'GAP_ANALYSIS_VIEWED',
      resource: 'GapAnalysisReport',
      resourceId: report.reportId,
      description: `${req.user.name} viewed Gap Analysis Report ${report.reportId}`,
      ipAddress: req.ip || '127.0.0.1',
      userAgent: req.headers['user-agent'] || '',
    });

    res.status(200).json({
      success: true,
      data: report,
    });
  } catch (error) {
    logger.error(`Get gap analysis report by ID error: ${error.message}`);
    res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * 4. DISPATCH / SEND REPORT TO RESPONSIBLE DEPARTMENT
 * @route POST /api/gap-analysis/:id/send
 * @access Admin only
 */
const sendReport = async (req, res) => {
  try {
    const { id } = req.params;
    const { departmentCode, adminMessage } = req.body;

    const report = await GapAnalysisReport.findOne({
      $or: [{ reportId: id }, { _id: id.match(/^[0-9a-fA-F]{24}$/) ? id : null }],
    });

    if (!report) {
      return res.status(404).json({
        success: false,
        message: 'Gap Analysis Report not found.',
      });
    }

    // If Admin overrides department
    if (departmentCode && departmentCode !== report.responsibleDepartment.code) {
      const targetDept = await Department.findOne({ code: departmentCode.toUpperCase() });
      if (targetDept) {
        report.responsibleDepartment = {
          code: targetDept.code,
          name: targetDept.name,
          contactEmail: targetDept.contactEmail,
          nodalOfficer: targetDept.nodalOfficer,
          departmentId: targetDept._id,
        };
      }
    }

    report.status = 'SENT';
    report.adminMessage = adminMessage || report.adminMessage || 'Please review surveillance gaps and evaluate camera deployment requirements.';
    report.sentAt = new Date();
    report.sentBy = {
      userId: req.user._id,
      name: req.user.name,
    };

    report.statusHistory.push({
      status: 'SENT',
      changedAt: new Date(),
      changedBy: req.user.name,
      notes: `Report officially dispatched to ${report.responsibleDepartment.name} with instructions: "${report.adminMessage}"`,
    });

    await report.save();

    // 1. Create Department Notification
    await Notification.create({
      recipientDepartment: report.responsibleDepartment.code,
      recipientRole: 'ALL',
      senderUser: req.user._id,
      senderName: req.user.name,
      senderDepartment: 'Home Department (Admin)',
      title: `Surveillance Gap Analysis Dispatched: ${report.reportId}`,
      message: `Admin has dispatched Gap Analysis for ${report.location.name} (${report.radiusMeters >= 1000 ? (report.radiusMeters / 1000).toFixed(1) + ' km' : report.radiusMeters + ' m'} radius). Coverage Score: ${report.summary.coverageScore}/100. Critical Gaps: ${report.summary.criticalGaps}.`,
      type: 'GAP_ANALYSIS_REPORT',
      priority: report.summary.criticalGaps > 0 ? 'urgent' : 'high',
      actionUrl: `/reports?tab=gap-analysis&id=${report.reportId}`,
    });

    // 2. Record Audit Log
    await SystemAuditLog.create({
      user: req.user._id,
      userName: req.user.name,
      userEmail: req.user.email,
      role: 'ADMIN',
      department: req.user.department || 'Government of Gujarat',
      action: 'GAP_ANALYSIS_SENT',
      resource: 'GapAnalysisReport',
      resourceId: report.reportId,
      description: `Dispatched Gap Analysis Report ${report.reportId} to ${report.responsibleDepartment.name}. Score: ${report.summary.coverageScore}/100, Critical Gaps: ${report.summary.criticalGaps}`,
      ipAddress: req.ip || '127.0.0.1',
      userAgent: req.headers['user-agent'] || '',
    });

    res.status(200).json({
      success: true,
      message: `Report ${report.reportId} dispatched to ${report.responsibleDepartment.name} successfully.`,
      data: report,
    });
  } catch (error) {
    logger.error(`Send gap analysis report error: ${error.message}`);
    res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * 5. UPDATE REPORT STATUS (Department Acknowledgement & Resolution)
 * @route PATCH /api/gap-analysis/:id/status
 * @access Authenticated (Department Users or Admin)
 */
const updateReportStatus = async (req, res) => {
  try {
    const { id } = req.params;
    const { status, message } = req.body;
    const userRole = String(req.user.role || '').toUpperCase();
    const isAdmin = ['ADMIN', 'SUPERADMIN'].includes(userRole);

    const validStatuses = ['ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED'];
    if (!validStatuses.includes(status)) {
      return res.status(400).json({
        success: false,
        message: `Invalid status. Must be one of: ${validStatuses.join(', ')}`,
      });
    }

    const report = await GapAnalysisReport.findOne({
      $or: [{ reportId: id }, { _id: id.match(/^[0-9a-fA-F]{24}$/) ? id : null }],
    });

    if (!report) {
      return res.status(404).json({
        success: false,
        message: 'Gap Analysis Report not found.',
      });
    }

    // Role check: Department user can only modify reports assigned to their department
    if (!isAdmin) {
      const userDept = (req.user.department || '').toUpperCase();
      const reportDept = (report.responsibleDepartment?.code || '').toUpperCase();
      const reportDeptName = (report.responsibleDepartment?.name || '').toUpperCase();

      const isMatchingDept =
        userDept &&
        (userDept === reportDept ||
          reportDeptName.includes(userDept) ||
          userDept.includes(reportDept));

      if (!isMatchingDept) {
        return res.status(403).json({
          success: false,
          message: 'Access Restricted: You cannot update gap analysis reports assigned to another department.',
        });
      }
    }

    report.status = status;

    if (status === 'ACKNOWLEDGED' && !report.acknowledgedAt) {
      report.acknowledgedAt = new Date();
      report.acknowledgedBy = {
        userId: req.user._id,
        name: req.user.name,
        department: req.user.department || report.responsibleDepartment.name,
      };
    }

    if (status === 'RESOLVED') {
      report.resolvedAt = new Date();
      report.resolvedBy = {
        userId: req.user._id,
        name: req.user.name,
      };
    }

    const noteText = message || `Status changed to ${status} by ${req.user.name}`;

    report.statusHistory.push({
      status,
      changedAt: new Date(),
      changedBy: req.user.name,
      notes: noteText,
    });

    if (message) {
      report.departmentResponses.push({
        message,
        senderId: req.user._id,
        senderName: req.user.name,
        senderRole: req.user.role,
        senderDepartment: req.user.department || report.responsibleDepartment.name,
        timestamp: new Date(),
      });
    }

    await report.save();

    // If updated by department user, notify Admin
    if (!isAdmin) {
      await Notification.create({
        recipientDepartment: 'POLICE',
        recipientRole: 'ADMIN',
        senderUser: req.user._id,
        senderName: req.user.name,
        senderDepartment: req.user.department || report.responsibleDepartment.name,
        title: `Gap Analysis Status Updated: ${report.reportId} (${status})`,
        message: `${req.user.name} (${report.responsibleDepartment.name}) updated status to ${status}. ${message ? `Note: "${message}"` : ''}`,
        type: 'GAP_ANALYSIS_STATUS_CHANGED',
        priority: 'medium',
        actionUrl: `/reports?tab=gap-analysis&id=${report.reportId}`,
      });
    }

    // Record Audit Log
    await SystemAuditLog.create({
      user: req.user._id,
      userName: req.user.name,
      userEmail: req.user.email,
      role: req.user.role,
      department: req.user.department || 'Government of Gujarat',
      action: 'GAP_ANALYSIS_STATUS_UPDATED',
      resource: 'GapAnalysisReport',
      resourceId: report.reportId,
      description: `Report ${report.reportId} status updated to ${status} by ${req.user.name}`,
      ipAddress: req.ip || '127.0.0.1',
      userAgent: req.headers['user-agent'] || '',
    });

    res.status(200).json({
      success: true,
      message: `Report status successfully updated to ${status}.`,
      data: report,
    });
  } catch (error) {
    logger.error(`Update gap analysis status error: ${error.message}`);
    res.status(500).json({ success: false, message: error.message });
  }
};

module.exports = {
  runAnalysis,
  getReports,
  getReportById,
  sendReport,
  updateReportStatus,
};
